# Generated by Django 3.1.7 on 2021-03-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='date_introduced',
            new_name='first_appearance',
        ),
    ]
